### ISSUE TITLE
Can't open file log

### ISSUE THREAD

**Issue by varkadov** [gdeOo/sublime-sourcetree#1]
With SourceTree version 2.0.5.8 just open SourceTree and don't open file log

**Comment by ghost** [comment]
Have the same problem, @gdeOo is this feature is still working?

**Comment by alnorth** [comment]
Same problem here. My console output:

```
reloading plugin SourceTreeCommands.sublime-sourcetree
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "sublime-sourcetree in /Users/alasdair/Library/Application Support/Sublime Text 3/Installed Packages/SourceTreeCommands.sublime-package", line 100, in run
  File "sublime-sourcetree in /Users/alasdair/Library/Application Support/Sublime Text 3/Installed Packages/SourceTreeCommands.sublime-package", line 68, in execute_sourcetree_cmd
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied
no command for selector: noop:

```
